version: '3'
services:
  auth-service:
    build:
      context: src/auth-service
      args:
        NODE_ENV: production
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017/
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  data-service:
    build:
      context: src/data-service
      args:
        NODE_ENV: production
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017/
    ports:
      - "3002:3002"
    depends_on:
      - mongo

  frontend:
    build:
      context: src/frontend
    ports:
      - "80:3000"
    depends_on:
      - auth-service
      - data-service

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mydatabase

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydatabase

volumes:
  data:

networks:
  code_coverage:
    external: true
