version: '3'
services:  
  auth-service:
    build:
      context: src/auth-service
      args:
        NODE_ENV: production
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017/
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  data-service:
    build:
      context: src/data-service
      args:
        NODE_ENV: production
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017/
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  frontend:
    build:
      context: src/frontend
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - data-service

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

volumes:
  data:

networks:
    code_coverage:
        external: true